=== VSydorenko/prro_docs/ЄВПЕЗ (Єдине вікно)/Схеми XSD/ticket01.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="DGStr128">
		<xs:restriction base="xs:string">
			<xs:maxLength value="128"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="TICKET" type="TicketContent"/>
	<xs:complexType name="TicketContent">
		<xs:sequence>
			<!--Óí³êàëüíèé ³äåíòèô³êàòîð äîêóìåíòà (GUID, îáîâ’ÿçêîâèé)-->
			<xs:element name="UID" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<!--Äàòà îïåðàö³¿ (ddmmyyyy, îáîâ’ÿçêîâèé)-->
			<xs:element name="ORDERDATE" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
			<!--×àñ îïåðàö³¿ (hhmmss, îáîâ’ÿçêîâèé)-->
			<xs:element name="ORDERTIME" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
			<!--Ëîêàëüíèé íîìåð äîêóìåíòà (128 ñèìâîë³â, îáîâ’ÿçêîâèé)-->
			<xs:element name="ORDERNUM" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
			<!--Ô³ñêàëüíèé íîìåð äîêóìåíòà (128 ñèìâîë³â, íåîáîâ’ÿçêîâèé)-->
			<xs:element name="ORDERTAXNUM" type="DGStr128" minOccurs="0" maxOccurs="1"/>
			<!--²äåíòèô³êàòîð îôëàéí ñåñ³¿ (128 ñèìâîë³â, íåîáîâ’ÿçêîâèé)-->
			<xs:element name="OFFLINESESSIONID" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
			<!--"Ñåêðåòíå ÷èñëî" äëÿ îá÷èñëåííÿ ô³ñêàëüíîãî íîìåðà îôëàéí äîêóìåíòà (128 ñèìâîë³â, íåîáîâ’ÿçêîâèé)-->
			<xs:element name="OFFLINESEED" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
			<!--Êîä ïîìèëêè (Ö³ëå ÷èñëî >= 0, íåîáîâ’ÿçêîâèé)-->
			<xs:element name="ERRORCODE" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<!--Òåêñò ïîìèëêè (òåêñò, íåîáîâ’ÿçêîâèé)-->
			<xs:element name="ERRORTEXT" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<!--Âåðñ³ÿ ôîðìàòó äîêóìåíòà (÷èñëîâèé, îáîâ’ÿçêîâèé)-->
			<xs:element name="VER" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== VSydorenko/prro_docs/Приклади/приклади/ticket01.xml
<?xml version="1.0" encoding="windows-1251"?>
<TICKET xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ticket01.xsd">
	<!--Унікальний ідентифікатор документа (GUID, обов’язковий)-->
	<UID>F32EE0EF-F8EE-46BD-9943-881AF3F982F5</UID>
	<!--Дата операції (ddmmyyyy, обов’язковий)-->
	<ORDERDATE>18112015</ORDERDATE>
	<!--Час операції (hhmmss, обов’язковий)-->
	<ORDERTIME>201543</ORDERTIME>
	<!--Локальний номер документа (128 символів, обов’язковий)-->
	<ORDERNUM>12345678</ORDERNUM>
	<!--Фіскальний номер документа (128 символів, необов’язковий)-->
	<ORDERTAXNUM>101234567890123</ORDERTAXNUM>
	<!--Ідентифікатор офлайн сесії (128 символів, обов’язковий)-->
	<OFFLINESESSIONID>2378946</OFFLINESESSIONID>
	<!--"Секретне число" для обчислення фіскального номера офлайн документа (128 символів, обов’язковий)-->
	<OFFLINESEED>293573240985</OFFLINESEED>
	<!--Код помилки (Ціле число >= 0, обов’язковий)-->
	<ERRORCODE>1</ERRORCODE>
	<!--Текст помилки (Текст, обов’язковий)-->
	<ERRORTEXT>РРО з фіскальним номером 123 не зареєстрований</ERRORTEXT>
	<!--Версія формату документа (числовий)-->
	<VER>1</VER>
</TICKET>
